### PR TITLE
Added Emotional Damage, untested

### PR DESCRIPTION
**Pull request by LeahHynes**
Added my bot to send a gif using the command !damage, which will send a randomized gif. Untested as of commit.

### CODE REVIEW

**Comment by hamzahap** [comment]
I would suggest using some kind of hosting for the gif images instead of adding them directly.
And also check the Ping plugin and use it as a sample plugin to use the correct file formatting and tings.

**Comment by hamzahap** [comment]
And also, gifint always == 1 will give the same result.....

**Comment by TylerHynes** [comment]
Apologies if anything is wrong, additionally I was using ping as a
reference.

**Comment by TylerHynes** [comment]
gifint should be randomized every time using randint

**Comment by TylerHynes** [comment]
oh, i didnt change the numbers when i copied the if block, my bad

**Review by jackharrhy — CHANGES_REQUESTED** [review]
+1 to hkings review, preferably you'd host the files elsewhere since this PR would add 10mb+ of data to the repository (its quite small, not really a place for general storage of larger data blobs)

and yeah, change the value in the if/else so you cover the cases where it is 2 & 3

**Review by jackharrhy — APPROVED** [review]

**Pull request merged**
